### ISSUE TITLE
Missing scrollbar Firefox 51.0.1

### ISSUE THREAD

**Issue by alvianx** [newhoa/victory-gtk-theme#1]
Just wanna say that I love the victory theme! but I found some issue as you see on the screenshot

1. The scrollbar is not visible on firefox 51.0.1, I can use the scrollbar anyway, but still it's not visible
2. Context menu has no border. (?) I'm not sure this is a feature or a bug
3. Inconsistent scrollbar, some app has fat boxy scrollbar and some has slim rounded 

![screenshot_2017-02-07_06-46-11](https://cloud.githubusercontent.com/assets/16168046/22671494/27706fcc-ed01-11e6-999b-8c1a242e75fd.png)

**Comment by newhoa** [comment]
Hey thanks, and thanks for adding a picture too. Yeah, I noticed that myself. I'm in the process of redoing the scrollbars and it should end up fixing this issue. I'll try to have it updated by the end of the week.

**Comment by newhoa** [comment]
Hey sorry for the late update. I updated it, then Firefox changed and broke my theme changed, then I updated it again and lost the changes in a hard drive failure! So it took a while but it should be relatively fixed now!
