### ISSUE TITLE
Uncolored Menubar in victory-16.10-gtk2-dark theme

### ISSUE THREAD

**Issue by chuutatsu** [newhoa/victory-gtk-theme#2]
**Reporter info**
 ```
 * Distribution - Manjaro 17.0.1
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Xfce
 ```
**Theme version** Latest from this Github, using **victory-16.10-gtk2-dark** theme

**Affected apps** File-Roller, Engrampa, Transmission, Google Chrome (and probably other (GTK+3) apps, I haven't check all but I assume that they suffer too)

**Actual issue**
When using **victory-16.10-gtk2-dark** theme, the menubar of GTK+3 apps is not matching with its window manager color. Strangely it only matches in Thunar app.
![1](https://cloud.githubusercontent.com/assets/24815847/26750269/52ac3c78-4848-11e7-9608-3ea78a71b880.png)
(Menubar matches with window manager - only in Thunar)

**Steps to reproduce** Open certain apps that I mentioned above after applying the full suite of **victory-16.10-gtk2-dark** (gtk and window manager themes).

**Expected behaviour** Menubar is colored and matched window manager's color -- in every applications (not only Thunar). Like this:
![1](https://cloud.githubusercontent.com/assets/24815847/26750269/52ac3c78-4848-11e7-9608-3ea78a71b880.png)

**Other Note** I was able to fix this a bit by editing the gtk-widgets.css file and modify the menubar. It would be very nice if you implement the fix into the next version of the theme.

**Comment by newhoa** [comment]
This should be fixed, give it a try and let me know. Gtk3 apps that combine the title bars with the menu system will still default to the original Victory (near-white) variant. That would require a lot more effort which I may work on in the future. But apps like Transmission, File-Roller, etc that are Openbox and XFWM4-friendly should match the Gtk theme. I also changed the names of some of the variant themes so be sure to delete or move the old ones before downloading and trying the new ones. Thanks for letting me know and thanks for the pictures and good description!
