### ISSUE TITLE
GTK 3.22+ support

### ISSUE THREAD

**Issue by Vistaus** [newhoa/victory-gtk-theme#4]
It would be great if you could support GTK 3.22 and higher 'cause I love this theme and miss it on 3.22 :) Esp. the light variant from the main screenshot would be great to have on 3.22+

**Comment by newhoa** [comment]
Thanks I'm glad you like it! Would you mind posting a screenshot of what it looks like on GTK 3.22? I thought GNOME was done breaking themes after GTK 3.20 but maybe they're still doing it. If it's something that needs a lot of work it may unfortunately have to wait till I update to GTK 3.22 and have more time to work with it which may be a few more months.

**Comment by Vistaus** [comment]
I see that you've updated the theme today and now it does look good on GTK 3.22, thank you for that! :) The only small issue now it that the titlebars of GTK3 apps are huge.

![screenshot from 2017-08-02 10 49 48](https://user-images.githubusercontent.com/1716229/28865480-618bacea-7770-11e7-9adf-231162dccead.png)

**Comment by newhoa** [comment]
Thanks for the screenshot. Glad the Gtk 3.22 issue worked itself out. As for the titlebars, I see what you mean, I'll keep that in mind for the next update. For now you can change the settings in the theme's Gtk-3.20/gtk-widgets.css file under headerbar, (line 1170) and adjust the padding to something lower than 8px. I'll go ahead and close this issue but if you have any other problems or anything just let me know! Thanks!

**Comment by Vistaus** [comment]
Thanks in advance for fixing it in the next update and thanks for providing a workaround for now! :smile:
