### ISSUE TITLE
Add Xfce Notification theme

### ISSUE THREAD

**Issue by chuutatsu** [newhoa/victory-gtk-theme#5]
I'm reusing this theme again, and found out that there is a lot of improvements since my last time of using it. 

However, this theme is still lacking a proper Xfce Notification theme. Would you add it in the future? Thanks in advance!

**Comment by newhoa** [comment]
Hey, glad you like the update. Thanks for pointing that out, I had an Xfce notification theme in there but I didn't realized they'd switched to Gtk3 for notifications already.

I added it in there, just select it from the notification settings. Let me know if there are any problems with it. Thanks!
