### ISSUE TITLE
Missing Icon: Open Folder - Tree View

### ISSUE THREAD

**Issue by Jazqa** [newhoa/victory-gtk-theme#6]
First of all, great job with the themes! Love both the icon and the GTK theme. I've used them on both of my computers for a day now and I've noticed no issues other than the one missing icon in Thunar (gconf folder in the picture).

![2017-10-16-224123_944x513_scrot](https://user-images.githubusercontent.com/18004783/31631715-36ad3dde-b2c3-11e7-8254-f46bc0435f27.png)

When using the detailed list the bar with Name Size and Type looks a little weird as well, but I think it's styled from the buttons, so it's understandable.

**Comment by newhoa** [comment]
Hey, thanks for the pic! I fixed the missing folder icon so be sure to update or redownload the icon theme. Or if you don't want to do that just go to the victory-icon-theme/places/16/ folder and make a copy of the folder-drag-accept.svg and rename the copy to folder-open.svg. That should fix it.

The sort bars use the style from a very old version of the Victory theme. I never changed them and I probably won't do much changing to the gtk2 theme at this point with most everything moving to Gtk3. If you'd like to change it you can open the file

` Victory-17.04/gtk-2.0/gtkrc`

and search for the line 

`style "treeview-header" = "default"`

under that there is a line that says gradient_shades. If you'd like it flat change them to 1.0,1.0,1.0,1.0. Or if you want it flat and white 1.1,1.1,1.1,1.1.

I might change this in the next update but I'm not sure. I was actually thinking of bringing back the rounded buttons here and there but I'm still not sure.

Anyway, thanks again and let me know if you have any more problems!
